import logging
import os
from datetime import datetime
from uuid import uuid4


_logging_initialized = False

def setup_logging(log_level: str = "INFO") -> logging.Logger:
    global _logging_initialized
    
    logger = logging.getLogger("hermes_office_agent")
    logger.setLevel(log_level)
    
    # 使用全局标志确保只初始化一次
    if _logging_initialized:
        return logger
    
    # 双重检查：确保没有已存在的 handler
    if logger.handlers:
        _logging_initialized = True
        return logger
    
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    
    # 设置控制台处理器，支持 UTF-8 编码
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    # 修复 Windows 控制台编码问题
    if hasattr(console_handler.stream, 'encoding'):
        console_handler.stream.reconfigure(encoding='utf-8')
    logger.addHandler(console_handler)
    
    os.makedirs("logs", exist_ok=True)
    # 文件处理器也设置为 UTF-8
    file_handler = logging.FileHandler("logs/combined.log", encoding='utf-8')
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
    
    _logging_initialized = True
    return logger


def safe_log_string(text: str) -> str:
    """
    安全的日志字符串处理函数，移除或替换无法在控制台显示的字符
    """
    if text is None:
        return ""
    
    # 替换常见的 emoji 字符
    emoji_map = {
        '👋': '[wave]',
        '😊': '[smile]',
        '🎉': '[party]',
        '❤️': '[heart]',
        '👍': '[thumbsup]',
        '👏': '[clap]',
        '🔥': '[fire]',
        '💡': '[lightbulb]',
        '✅': '[ok]',
        '❌': '[no]',
        '⚠️': '[warn]',
        '❓': '[question]',
        '💪': '[strong]',
        '🌟': '[star]',
        '🎯': '[target]',
        '💬': '[chat]',
        '📝': '[note]',
        '📊': '[chart]',
        '🔍': '[search]',
        '🚀': '[rocket]',
        '💻': '[computer]',
        '📱': '[phone]',
        '🔧': '[wrench]',
        '⚙️': '[gear]',
        '📦': '[package]',
        '🔒': '[lock]',
        '🔑': '[key]',
        '📧': '[email]',
        '📤': '[send]',
        '📥': '[receive]',
        '🔄': '[refresh]',
        '⏳': '[hourglass]',
        '⌛': '[clock]',
        '📅': '[calendar]',
        '📈': '[trendup]',
        '📉': '[trenddown]',
        '🎨': '[palette]',
        '🎭': '[mask]',
        '🎪': '[tent]',
        '🎬': '[film]',
        '🎮': '[game]',
        '🎵': '[music]',
        '🎶': '[note]',
        '🏆': '[trophy]',
        '🎯': '[target]',
        '🎲': '[dice]',
        '🎸': '[guitar]',
        '🎹': '[piano]',
        '🎺': '[trumpet]',
        '🎻': '[violin]',
        '🥁': '[drum]',
        '🎤': '[mic]',
        '🎧': '[headphones]',
        '📷': '[camera]',
        '🎬': '[clapper]',
        '🎨': '[brush]',
        '✍️': '[pen]',
        '📚': '[books]',
        '📖': '[book]',
        '📗': '[greenbook]',
        '📘': '[bluebook]',
        '📙': '[yellowbook]',
        '📕': '[redbook]',
        '📔': '[notebook]',
        '📒': '[memo]',
        '📓': '[notepad]',
        '📑': '[bookmark]',
        '🔖': '[tag]',
        '🏷️': '[label]',
        '📁': '[folder]',
        '📂': '[openfolder]',
        '📄': '[file]',
        '📋': '[clipboard]',
        '📝': '[edit]',
        '✏️': '[pencil]',
        '🔏': '[sealed]',
        '🔐': '[locked]',
        '🔓': '[unlocked]',
        '🔑': '[key]',
        '🗝️': '[oldkey]',
        '🚪': '[door]',
        '🏠': '[house]',
        '🏢': '[building]',
        '🏬': '[store]',
        '🏭': '[factory]',
        '🌍': '[globe]',
        '🌎': '[earth]',
        '🌏': '[asia]',
        '🗺️': '[map]',
        '📍': '[pin]',
        '🚗': '[car]',
        '🚙': '[suv]',
        '🚌': '[bus]',
        '🚎': '[trolley]',
        '🚐': '[van]',
        '🚚': '[truck]',
        '🚛': '[bigtruck]',
        '🚜': '[tractor]',
        '🚲': '[bike]',
        '🛵': '[scooter]',
        '🏍️': '[motorcycle]',
        '🚁': '[helicopter]',
        '✈️': '[plane]',
        '🛫': '[departure]',
        '🛬': '[arrival]',
        '🚀': '[rocket]',
        '🛸': '[ufo]',
        '🚢': '[ship]',
        '⛵': '[sailboat]',
        '🛶': '[canoe]',
        '🚤': '[speedboat]',
        '⚓': '[anchor]',
        '🚡': '[tram]',
        '🚠': '[gondola]',
        '🚟': '[monorail]',
        '🚞': '[train]',
        '🚂': '[steam]',
        '🚆': '[metro]',
        '🚄': '[bullet]',
        '🚝': '[commuter]',
        '🚇': '[subway]',
        '🚉': '[station]',
        '🛒': '[shopping]',
        '💰': '[money]',
        '💴': '[yen]',
        '💵': '[dollar]',
        '💶': '[euro]',
        '💷': '[pound]',
        '💳': '[creditcard]',
        '🏧': '[atm]',
        '💸': '[cash]',
        '📲': '[mobile]',
        '☎️': '[phone]',
        '📞': '[call]',
        '📟': '[pager]',
        '📠': '[fax]',
        '🔌': '[plug]',
        '💡': '[bulb]',
        '🔦': '[flashlight]',
        '🕯️': '[candle]',
        '⚡': '[zap]',
        '🔋': '[battery]',
        '🔌': '[charger]',
        '💻': '[laptop]',
        '🖥️': '[desktop]',
        '🖨️': '[printer]',
        '🖱️': '[mouse]',
        '⌨️': '[keyboard]',
        '🖲️': '[trackball]',
        '💽': '[floppy]',
        '💾': '[save]',
        '💿': '[cd]',
        '📀': '[dvd]',
        '📁': '[folder]',
        '📂': '[folderopen]',
        '🗂️': '[filing]',
        '📊': '[barchart]',
        '📈': '[linechart]',
        '📉': '[decline]',
        '📋': '[report]',
        '🗒️': '[notepage]',
        '📝': '[writing]',
        '✍️': '[handwrite]',
        '📄': '[document]',
        '📃': '[page]',
        '📑': '[divider]',
        '🔖': '[bookmark]',
        '🏷️': '[price]',
        '📛': '[badge]',
        '🎫': '[ticket]',
        '🎟️': '[admission]',
        '📌': '[pushpin]',
        '📍': '[location]',
        '🏷️': '[tag]',
        '🔖': '[ribbon]',
        '📎': '[paperclip]',
        '📐': '[ruler]',
        '✂️': '[scissors]',
        '🗡️': '[sword]',
        '🔪': '[knife]',
        '⚔️': '[swords]',
        '🛡️': '[shield]',
        '🔧': '[wrench]',
        '⚙️': '[gear]',
        '🔩': '[bolt]',
        '🔨': '[hammer]',
        '⛏️': '[pickaxe]',
        '🔬': '[microscope]',
        '🔭': '[telescope]',
        '⚗️': '[flask]',
        '🧪': '[beaker]',
        '🧫': '[petri]',
        '📡': '[satellite]',
        '📶': '[signal]',
        '🛜': '[wifi]',
        '🔌': '[connection]',
        '🖧': '[network]',
        '🌐': '[internet]',
        '🔍': '[search]',
        '🔎': '[magnify]',
        '🧮': '[calculator]',
        '📊': '[stats]',
        '📈': '[growth]',
        '📉': '[loss]',
        '⏰': '[alarm]',
        '⏱️': '[stopwatch]',
        '⏲️': '[timer]',
        '🕐': '[1oclock]',
        '🕑': '[2oclock]',
        '🕒': '[3oclock]',
        '🕓': '[4oclock]',
        '🕔': '[5oclock]',
        '🕕': '[6oclock]',
        '🕖': '[7oclock]',
        '🕗': '[8oclock]',
        '🕘': '[9oclock]',
        '🕙': '[10oclock]',
        '🕚': '[11oclock]',
        '🕛': '[12oclock]',
        '📅': '[date]',
        '📆': '[calendar]',
        '🗓️': '[schedule]',
        '🎂': '[cake]',
        '🎉': '[celebration]',
        '🎊': '[confetti]',
        '🎁': '[gift]',
        '🎈': '[balloon]',
        '🎀': '[bow]',
        '🏆': '[award]',
        '🥇': '[gold]',
        '🥈': '[silver]',
        '🥉': '[bronze]',
        '🎯': '[goal]',
        '⚽': '[soccer]',
        '🏀': '[basketball]',
        '🏈': '[football]',
        '⚾': '[baseball]',
        '🎾': '[tennis]',
        '🏐': '[volleyball]',
        '🏓': '[pingpong]',
        '🏸': '[badminton]',
        '🎱': '[billiards]',
        '🃏': '[cards]',
        '🎲': '[gambling]',
        '🎰': '[slot]',
        '🤝': '[handshake]',
        '👋': '[wave]',
        '🙋': '[raisehand]',
        '🙋‍♂️': '[manraisehand]',
        '🙋‍♀️': '[womanraisehand]',
        '🙌': '[handsup]',
        '👏': '[clap]',
        '🙏': '[pray]',
        '👍': '[thumbsup]',
        '👎': '[thumbsdown]',
        '✊': '[fist]',
        '🤛': '[leftfist]',
        '🤜': '[rightfist]',
        '🤞': '[crossfingers]',
        '🤟': '[iloveyou]',
        '🤘': '[rock]',
        '👌': '[okhand]',
        '👈': '[leftpoint]',
        '👉': '[rightpoint]',
        '👆': '[uppoint]',
        '👇': '[downpoint]',
        '☝️': '[indexup]',
        '✌️': '[victory]',
        '🤚': '[raisedhand]',
        '🖐️': '[palm]',
        '🖖': '[vulcan]',
        '👋': '[wavehand]',
        '🤝': '[shake]',
        '💪': '[muscle]',
        '🦾': '[robotarm]',
        '🦿': '[robotleg]',
        '🦵': '[leg]',
        '🦶': '[foot]',
        '👂': '[ear]',
        '👃': '[nose]',
        '👁️': '[eye]',
        '👀': '[eyes]',
        '👅': '[tongue]',
        '👄': '[mouth]',
        '👋': '[bye]',
        '😀': '[grin]',
        '😃': '[smiley]',
        '😄': '[laugh]',
        '😁': '[beaming]',
        '😆': '[laughing]',
        '😅': '[sweat]',
        '🤣': '[rofl]',
        '😂': '[tears]',
        '🙂': '[slight]',
        '😊': '[blush]',
        '😇': '[angel]',
        '🥰': '[heartface]',
        '😍': '[heart]',
        '🤩': '[star]',
        '😘': '[kiss]',
        '😗': '[kissing]',
        '😚': '[closedkiss]',
        '😋': '[yum]',
        '😛': '[stuckout]',
        '😝': '[tongue]',
        '🤑': '[money]',
        '🤗': '[hug]',
        '🤭': '[covermouth]',
        '🤫': '[shhh]',
        '🤔': '[thinking]',
        '🤐': '[zipper]',
        '🤨': '[raisedeyebrow]',
        '😐': '[neutral]',
        '😑': '[expressionless]',
        '😶': '[silent]',
        '😏': '[smirk]',
        '😒': '[unamused]',
        '🙄': '[roll]',
        '😬': '[grimace]',
        '🤥': '[liar]',
        '😌': '[relieved]',
        '😔': '[pensive]',
        '😪': '[sleepy]',
        '🤤': '[drool]',
        '😴': '[sleeping]',
        '😷': '[mask]',
        '🤒': '[thermometer]',
        '🤕': '[bandage]',
        '🤢': '[nauseated]',
        '🤮': '[vomiting]',
        '🥵': '[hot]',
        '🥶': '[cold]',
        '🥴': '[woozy]',
        '😵': '[dizzy]',
        '🤯': '[exploding]',
        '🤠': '[cowboy]',
        '🥳': '[partyface]',
        '🥸': '[disguise]',
        '😎': '[sunglasses]',
        '🤓': '[nerd]',
        '🧐': '[monocle]',
        '😕': '[confused]',
        '😟': '[worried]',
        '🙁': '[slightfrown]',
        '☹️': '[frown]',
        '😮': '[openmouth]',
        '😯': '[hushed]',
        '😲': '[astonished]',
        '😳': '[blushing]',
        '🥺': '[pleading]',
        '😦': '[frowning]',
        '😧': '[anguished]',
        '😨': '[fearful]',
        '😰': '[anxious]',
        '😥': '[sadrelief]',
        '😢': '[cry]',
        '😭': '[loudcry]',
        '😱': '[scream]',
        '😖': '[confounded]',
        '😣': '[persevering]',
        '😞': '[disappointed]',
        '😓': '[sweatsmile]',
        '😩': '[weary]',
        '😫': '[tired]',
        '🥱': '[yawning]',
        '😤': '[triumph]',
        '😡': '[angry]',
        '😠': '[mad]',
        '🤬': '[swearing]',
        '😈': '[smilingdevil]',
        '👿': '[angrydevil]',
        '💀': '[skull]',
        '☠️': '[skullcrossbones]',
        '💩': '[poop]',
        '🤡': '[clown]',
        '👹': '[ogre]',
        '👺': '[goblin]',
        '👻': '[ghost]',
        '👽': '[alien]',
        '👾': '[monster]',
        '🤖': '[robot]',
        '🎃': '[jackolantern]',
        '💀': '[skeleton]',
        '☠️': '[warning]',
        '💀': '[dead]',
        '⚰️': '[coffin]',
        '⚱️': '[urn]',
        '🧟': '[zombie]',
        '🧛': '[vampire]',
        '🧌': '[troll]',
        '👋': '[wavehello]',
    }
    
    # 替换 emoji
    for emoji, replacement in emoji_map.items():
        text = text.replace(emoji, replacement)
    
    return text


def generate_id() -> str:
    return str(uuid4())


def get_timestamp() -> int:
    return int(datetime.now().timestamp())


def ensure_directory(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def truncate_text(text: str, max_length: int = 500) -> str:
    if len(text) <= max_length:
        return text
    return text[:max_length] + "..."
